const NOW = Date.now();
const DAY = 86400000;

export const SEED_GRAPH = {
  topics: {
    chip_war: {
      title: "Chip War",
      type: "book",
      sessions: 4,
      totalMin: 180,
      confidence: 8,
      notes: [{ note: "Taiwan's TSMC controls 90% of advanced chips — biggest geopolitical chokepoint of our era. Apply this: find the irreplaceable node in any supply chain.", date: NOW - DAY * 5 }],
      firstSeen: NOW - DAY * 30,
      lastSeen: NOW - DAY * 2,
      connections: ["extreme_ownership", "the_new_map"],
    },
    extreme_ownership: {
      title: "Extreme Ownership",
      type: "book",
      sessions: 6,
      totalMin: 240,
      confidence: 9,
      notes: [{ note: "No bad teams, only bad leaders. Cover and move — every team member covers others. Decentralized command requires clarity of intent.", date: NOW - DAY * 10 }],
      firstSeen: NOW - DAY * 60,
      lastSeen: NOW - DAY * 7,
      connections: [],
    },
    ercot_energy: {
      title: "ERCOT Energy Markets",
      type: "topic",
      sessions: 2,
      totalMin: 90,
      confidence: 6,
      notes: [{ note: "Texas grid is islanded — peak demand pricing creates asymmetric opportunity in energy infrastructure and storage plays.", date: NOW - DAY * 3 }],
      firstSeen: NOW - DAY * 14,
      lastSeen: NOW - DAY * 3,
      connections: ["the_new_map"],
    },
    real_estate_underwriting: {
      title: "Real Estate Underwriting",
      type: "topic",
      sessions: 3,
      totalMin: 120,
      confidence: 7,
      notes: [],
      firstSeen: NOW - DAY * 45,
      lastSeen: NOW - DAY * 8,
      connections: [],
    },
    negotiation_psychology: {
      title: "Negotiation Psychology",
      type: "topic",
      sessions: 5,
      totalMin: 200,
      confidence: 8,
      notes: [{ note: "Tactical empathy beats logic in 90% of negotiations. Label the emotion, get a 'that's right', then move. The late-night FM DJ voice is the unlock.", date: NOW - DAY * 15 }],
      firstSeen: NOW - DAY * 90,
      lastSeen: NOW - DAY * 12,
      connections: ["never_split_the_difference"],
    },
    dividend_investing: {
      title: "Dividend Investing Strategy",
      type: "topic",
      sessions: 2,
      totalMin: 80,
      confidence: 5,
      notes: [],
      firstSeen: NOW - DAY * 20,
      lastSeen: NOW - DAY * 18,
      connections: [],
    },
  },
  sessions: [
    { title: "Chip War",                    type: "book",  date: NOW - DAY * 2,  durationMin: 45, confidence: 8 },
    { title: "ERCOT Energy Markets",        type: "topic", date: NOW - DAY * 3,  durationMin: 60, confidence: 6 },
    { title: "Extreme Ownership",           type: "book",  date: NOW - DAY * 7,  durationMin: 40, confidence: 9 },
    { title: "Real Estate Underwriting",    type: "topic", date: NOW - DAY * 8,  durationMin: 50, confidence: 7 },
    { title: "Negotiation Psychology",      type: "topic", date: NOW - DAY * 12, durationMin: 55, confidence: 8 },
    { title: "Dividend Investing Strategy", type: "topic", date: NOW - DAY * 18, durationMin: 40, confidence: 5 },
  ],
  totalTime: 910,
  streak: 5,
  lastSeen: NOW - DAY * 2,
};

export const SEED_PROJECTS = [
  {
    id: "proj_1",
    title: "Real Estate Cash Flow System",
    emoji: "🏘",
    status: "active",
    category: "finance",
    color: "#00FFB2",
    description: "Build $10K+/mo passive income through strategic Houston-area real estate acquisitions. Target: duplex/triplex value-add plays within 30min of downtown.",
    milestones: [
      { id: "m1", text: "Complete market analysis — zip codes 77002, 77006, 77007", done: true },
      { id: "m2", text: "Underwriting model built + validated on 5 comps", done: true },
      { id: "m3", text: "First property LOI submitted", done: false },
      { id: "m4", text: "Financing stack locked (DSCR + conventional)", done: false },
      { id: "m5", text: "Close first deal", done: false },
    ],
    connections: ["Essays of Warren Buffett", "Real Estate Underwriting", "The Snowball Effect"],
    blueOcean: "Focus on 1970s-80s small multifamily in transitioning neighborhoods — overlooked by institutional buyers, perfect for value-add BRRRR",
    createdAt: NOW - DAY * 45,
    updatedAt: NOW - DAY * 2,
    priority: "high",
  },
  {
    id: "proj_2",
    title: "BD Pipeline Optimization",
    emoji: "🤝",
    status: "active",
    category: "business",
    color: "#6366F1",
    description: "Systematize BD process to compound deal flow. Build referral network, track conversion rates, identify highest-leverage prospect profiles.",
    milestones: [
      { id: "m1", text: "CRM audit + data hygiene", done: true },
      { id: "m2", text: "Ideal Customer Profile (ICP) defined", done: true },
      { id: "m3", text: "Referral partner program designed", done: true },
      { id: "m4", text: "90-day outreach cadence launched", done: false },
      { id: "m5", text: "Measure and optimize at 30/60/90 days", done: false },
    ],
    connections: ["Never Split the Difference", "Influence", "Negotiation Psychology"],
    blueOcean: "Specialize in a vertical niche where you have unique insight — becomes an unfair advantage in every BD conversation",
    createdAt: NOW - DAY * 60,
    updatedAt: NOW - DAY * 5,
    priority: "high",
  },
  {
    id: "proj_3",
    title: "Dividend Portfolio — $5K/mo Target",
    emoji: "💰",
    status: "planning",
    category: "finance",
    color: "#ffcc44",
    description: "Build dividend income stream targeting $5K/mo within 5 years. Focus on REITs, dividend growth stocks, covered calls overlay to generate extra yield.",
    milestones: [
      { id: "m1", text: "Portfolio strategy document locked", done: true },
      { id: "m2", text: "Brokerage accounts structured (taxable + IRA)", done: false },
      { id: "m3", text: "Initial 10 positions selected + researched", done: false },
      { id: "m4", text: "Monthly DCA plan automated", done: false },
    ],
    connections: ["Essays of Warren Buffett", "The Snowball Effect", "Thinking Fast and Slow"],
    blueOcean: "Covered calls on high-dividend positions generates 3-5% additional annual yield — few retail investors do this systematically",
    createdAt: NOW - DAY * 20,
    updatedAt: NOW - DAY * 10,
    priority: "medium",
  },
  {
    id: "proj_4",
    title: "Health Protocol 2025",
    emoji: "⚡",
    status: "active",
    category: "health",
    color: "#ff8844",
    description: "Implement Attia/Huberman longevity framework. Zone 2 training, strength base, sleep optimization, quarterly bloodwork tracking.",
    milestones: [
      { id: "m1", text: "Baseline bloodwork panel (NMR lipids, hs-CRP, HbA1c, testosterone)", done: true },
      { id: "m2", text: "Zone 2 protocol — 3x/week, 45 min", done: true },
      { id: "m3", text: "Strength program — 3x/week compound lifts", done: true },
      { id: "m4", text: "Sleep hygiene locked (8hr target, consistent schedule)", done: false },
      { id: "m5", text: "90-day follow-up bloodwork + compare", done: false },
    ],
    connections: ["Tools of Titans", "Man's Search for Meaning"],
    blueOcean: "Longevity as competitive advantage — optimize for healthspan to 90+, not just today's performance",
    createdAt: NOW - DAY * 90,
    updatedAt: NOW - DAY * 1,
    priority: "high",
  },
];

export const SEED_NOTES = [
  {
    id: "note_1",
    title: "Chip War → Real Estate Connection",
    content: "The TSMC chokepoint model applies perfectly to real estate: find the one neighborhood everyone has to come through. In Houston, that's the Inner Loop. Control irreplaceable supply, not commodity supply. Buffett + Miller → same principle, different asset class. The insight: monopoly-adjacent positioning compounds, competition just grinds.",
    tags: ["systems", "real-estate", "mental-models"],
    connections: ["Chip War", "Essays of Warren Buffett", "Real Estate Cash Flow System"],
    createdAt: NOW - DAY * 4,
    color: "#00FFB2",
  },
  {
    id: "note_2",
    title: "Voss Negotiation Principle → BD",
    content: "Late-night FM DJ voice + calibrated questions. In BD: never ask yes/no questions. 'How am I supposed to do that?' is more powerful than any counter-offer. The goal is them talking, not you talking. Label their frustration before you pitch. Decisive bet: 80% of BD deals are won before the formal pitch — won in the discovery conversation.",
    tags: ["negotiation", "bd", "mental-models"],
    connections: ["Never Split the Difference", "BD Pipeline Optimization"],
    createdAt: NOW - DAY * 12,
    color: "#ff4488",
  },
  {
    id: "note_3",
    title: "Compounding Applies to Relationships",
    content: "Snowball + 7 Habits synthesis: trust is compound interest. One honest interaction = small deposit. Consistent honesty over years = unfair social capital advantage. Rakowich's humility point: leaders who don't need credit get more credit. Paradox of generosity — the more you give away, the more returns. This is the real W2 protection play.",
    tags: ["relationships", "leadership", "compounding"],
    connections: ["The Snowball Effect", "Transfluence", "7 Habits"],
    createdAt: NOW - DAY * 18,
    color: "#6366F1",
  },
  {
    id: "note_4",
    title: "Blue Ocean Formula for Houston Real Estate",
    content: "Most investors fight over: fully-renovated single family homes in hot zip codes. Blue Ocean: 1970s-80s small multifamily (4-8 units) in transitioning neighborhoods where Airbnb isn't viable but long-term tenants are. No institutional competition, higher cap rates, value-add upside, BRRRR-able. The Chip War lesson: find the supply choke, not the commodity.",
    tags: ["real-estate", "blue-ocean", "houston"],
    connections: ["Chip War", "Real Estate Cash Flow System"],
    createdAt: NOW - DAY * 6,
    color: "#ffcc44",
  },
];

export const SEED_RESEARCH = [
  {
    id: "res_1",
    title: "Houston CRE Market 2025 Tipping Point",
    query: "Is Houston commercial real estate at a tipping point given energy sector recovery and population migration from coastal cities?",
    status: "active",
    createdAt: NOW - DAY * 7,
    tags: ["real-estate", "houston", "macro"],
    messages: [],
  },
  {
    id: "res_2",
    title: "AI Agents — Blue Ocean Opportunities",
    query: "Which industries will be most disrupted by AI agents in 18-36 months? Where are the Blue Ocean opportunities for a BD operator who understands both technology and relationships?",
    status: "active",
    createdAt: NOW - DAY * 3,
    tags: ["ai", "blue-ocean", "macro"],
    messages: [],
  },
  {
    id: "res_3",
    title: "Covered Calls Strategy Deep Dive",
    query: "How to systematically implement covered calls on a dividend stock portfolio to generate an additional 3-5% annual yield without sacrificing core income.",
    status: "saved",
    createdAt: NOW - DAY * 15,
    tags: ["finance", "options", "dividend"],
    messages: [],
  },
];
